# fly.toml app configuration for oramax-app
app = "oramax-app"
primary_region = "fra"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

  # Health check προς το /healthz (γρήγορο και «στενό» για άμεσο fail/auto-restart)
  [[http_service.checks]]
    method = "GET"
    path = "/healthz"
    interval = "10s"
    timeout = "2s"
    grace_period = "20s"
    protocol = "http"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
