# fly.toml app configuration for oramax-app
app = "oramax-app"
primary_region = "fra"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

  # Health check προς το /healthz
  [[http_service.checks]]
    method = "GET"
    path = "/healthz"
    interval = "15s"
    timeout = "3s"
    grace_period = "30s"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
